
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

group: !include_dir_merge_named groups/ # Group Definitions
automation: !include automations.yaml
script: !include scripts.yaml

zwave: !include_dir_merge_named zwave/ # Zwave Config
zone: !include_dir_merge_list zones/ # Zones
weather: !include_dir_merge_list weather/ # Weather Tracking
tts: !include_dir_merge_list tts/ # Text to speech
recorder: !include_dir_merge_named recorder/ # Historical Data
history: !include_dir_merge_list history/
octoprint: !include_dir_merge_named octoprint/ # 3D Printer
light: !include_dir_merge_list lights/ # Light Switches
switch: !include_dir_merge_list switches/
sensor: !include_dir_merge_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/
neato: !include_dir_merge_named robots/
media_player: !include_dir_merge_list media_players/
logbook: !include_dir_merge_named logbook/
google: !include_dir_merge_named google/
input_boolean: !include_dir_merge_named input_boolean/
life360: !include_dir_merge_named life360/
panel_iframe: !include_dir_merge_named panel_iframe/

#logger:
mqtt:
  broker: !secret mqtt_broker
  discovery: true
  username: !secret mqtt_username
  password: !secret mqtt_password
  discovery_prefix: homeassistant

custom_updater:
  track:
    - components
    - python_scripts
  component_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/custom_components.json
  python_script_urls:
    - https://raw.githubusercontent.com/pnbruckner/homeassistant-config/master/python_scripts.json

person:
system_health:
wemo:
  discovery: false
  static:
    - 192.168.1.60
    - 192.168.1.61

cast: !include_dir_merge_named cast/ # Google Media Players
    
discovery:
updater:
map:
sun:
ios: