- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: disk_use
      arg: /    
    - type: memory_free
    - type: disk_free
      arg: /
    - type: memory_use_percent
    - type: memory_use