- platform: group
  name: All lights
  entities:
    - light.kitchen
    - light.dining_room
    - light.living_room
    - light.master_bedroom
    - light.hall
    - light.entertainment_center
    - light.living_room_fan
    - light.patio_lights
    - light.master_closet
    - light.guest_bath
    - light.guest_bedroom