- platform: switch
  name: Patio Lights
  entity_id: switch.patio_lights

- platform: switch
  name: Entertainment Center
  entity_id: switch.entertainment_center

- platform: switch
  name: Jon's Desk Lamp
  entity_id: switch.desklamp2