- platform: imap_email_content
  server: imap.gmail.com
  port: 993
  username: !secret imap_username
  password: !secret imap_password
  senders:
    - no-reply@costco.com
  value_template: >-
    {% if 'Costco Membership Payment Confirmation' in subject %}
      Costo Membership Renewed
    {% endif %}