- platform: generic_thermostat
  name: Heating
  heater: switch.heat
  target_sensor: sensor.fan_am2301_temperature
  min_temp: 68
  max_temp: 78
  ac_mode: false
  target_temp: 78
  cold_tolerance: 0.3
  hot_tolerance: 0.3
  min_cycle_duration:
    seconds: 5
  initial_hvac_mode: "off"
  away_temp: 68
  precision: 0.1

- platform: generic_thermostat
  name: Cooling
  heater: switch.cool
  target_sensor: sensor.fan_am2301_temperature
  min_temp: 68
  max_temp: 80
  ac_mode: true
  target_temp: 78
  cold_tolerance: 0.3
  hot_tolerance: 0.3
  min_cycle_duration:
    seconds: 5
  initial_hvac_mode: "off"
  away_temp: 68
  precision: 0.1