- alias: Startup Notification
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: tts.google_translate_say
      entity_id: media_player.kitchen_speaker
      data:
        message: 'Home Assistant Online'



