- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

- platform: samsungtv
  host: !secret samsung_tv_1_host_ip
  name: Samsung TV
  mac: 0C:89:10:7E:0C:72

- platform: volumio
  name: SoundFX
  host: !secret volumio_host_ip_1
  port: 3000

- platform: volumio
  name: Music
  host: !secret volumio_host_ip_2
  port: 3000

#- platform: mpd
#  name: volumio_1_mpd
#  host: !secret volumio_host_ip_1

#- platform: mpd
#  name: volumio_2_mpd
#  host: !secret volumio_host_ip_2
